name: Run Automation Bot

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link to automate'
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v16
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run automation script
        run: node bot.js ${{ github.event.inputs.link }}